#!/usr/bin/env python3
"""Add more products to seed_data.py to reach 500+ total."""

NEW_PRODUCTS = [
    # OFFICE SUPPLIES (20)
    {"name": "A4 Copy Paper 500 sheets", "name_arabic": "ورق A4 (500 ورقة)", "category": "Office Supplies", "price": 12.0, "moq": 10, "stock": 2000},
    {"name": "Ballpoint Pen Box 50pc", "name_arabic": "قلم حبر كرتون (50 قلم)", "category": "Office Supplies", "price": 18.0, "moq": 5, "stock": 1000},
    {"name": "Sticky Notes 100pc", "name_arabic": "ملاحظات لاصقة (100 ورقة)", "category": "Office Supplies", "price": 8.0, "moq": 20, "stock": 500},
    {"name": "File Folder A4 100pc", "name_arabic": "مجلد A4 (100 مجلد)", "category": "Office Supplies", "price": 35.0, "moq": 5, "stock": 400},
    {"name": "Desk Organizer 5-Drawer", "name_arabic": "منظم مكتب 5 ادراج", "category": "Office Supplies", "price": 45.0, "moq": 2, "stock": 100},
    {"name": "Whiteboard 90x120cm", "name_arabic": "سبورة بيضاء 90x120", "category": "Office Supplies", "price": 120.0, "moq": 1, "stock": 30},
    {"name": "Marker Set 12 Colors", "name_arabic": "طقم ماركر 12 لون", "category": "Office Supplies", "price": 25.0, "moq": 5, "stock": 200},
    {"name": "Stapler Heavy Duty", "name_arabic": "درج ثقيل", "category": "Office Supplies", "price": 35.0, "moq": 3, "stock": 150},
    {"name": "Paper Shredder", "name_arabic": "_MACHINE ورق", "category": "Office Supplies", "price": 280.0, "moq": 1, "stock": 20},
    {"name": "Laminator A4", "name_arabic": "جهاز تغليف A4", "category": "Office Supplies", "price": 150.0, "moq": 1, "stock": 30},
    {"name": "Label Maker", "name_arabic": "جهاز طباعة ملصقات", "category": "Office Supplies", "price": 95.0, "moq": 1, "stock": 40},
    {"name": "Calculator Desktop", "name_arabic": "الة حاسبة مكتبية", "category": "Office Supplies", "price": 28.0, "moq": 5, "stock": 200},
    {"name": "Presentation Pointer", "name_arabic": "مؤشر عرض تقديمي", "category": "Office Supplies", "price": 45.0, "moq": 2, "stock": 100},
    {"name": "Ring Binder A4", "name_arabic": "مجلد حلقات A4", "category": "Office Supplies", "price": 5.0, "moq": 20, "stock": 1000},
    {"name": "Tape Dispenser", "name_arabic": "حامل شريط لاصق", "category": "Office Supplies", "price": 15.0, "moq": 5, "stock": 300},
    {"name": "Scissors 8-inch", "name_arabic": "مقص 8 بوصة", "category": "Office Supplies", "price": 8.0, "moq": 10, "stock": 500},
    {"name": "Paper Clips 1000pc", "name_arabic": "مشابك ورق (1000 مشبك)", "category": "Office Supplies", "price": 6.0, "moq": 10, "stock": 1000},
    {"name": "Rubber Bands 500g", "name_arabic": "مطاط (500 جرام)", "category": "Office Supplies", "price": 4.0, "moq": 20, "stock": 500},
    {"name": "Desk Lamp LED", "name_arabic": "مصباح مكتب LED", "category": "Office Supplies", "price": 55.0, "moq": 2, "stock": 100},
    {"name": "Ergonomic Chair", "name_arabic": "كرسي مريح", "category": "Office Supplies", "price": 350.0, "moq": 1, "stock": 20},
    # CLEANING (15)
    {"name": "Vacuum Cleaner Industrial", "name_arabic": "مكنسة كهربائية صناعية", "category": "Cleaning", "price": 450.0, "moq": 1, "stock": 20},
    {"name": "Mop Bucket Wringer", "name_arabic": "دلو ممسحة", "category": "Cleaning", "price": 35.0, "moq": 5, "stock": 150},
    {"name": "Glass Cleaner 5L", "name_arabic": "منظف زجاج 5 لتر", "category": "Cleaning", "price": 18.0, "moq": 10, "stock": 500},
    {"name": "Toilet Cleaner 1L", "name_arabic": "منظف حمام 1 لتر", "category": "Cleaning", "price": 6.0, "moq": 24, "stock": 1000},
    {"name": "Trash Bags 100pc", "name_arabic": "اكياس قمامة (100 كيس)", "category": "Cleaning", "price": 22.0, "moq": 10, "stock": 800},
    {"name": "Squeegee Floor 60cm", "name_arabic": "مسحاة ارضية 60 سم", "category": "Cleaning", "price": 25.0, "moq": 5, "stock": 200},
    {"name": "Microfiber Cloth 50pc", "name_arabic": "قماش مايكروفايبر (50)", "category": "Cleaning", "price": 30.0, "moq": 5, "stock": 300},
    {"name": "Pressure Washer 2000W", "name_arabic": "غسالة ضغط 2000 واط", "category": "Cleaning", "price": 650.0, "moq": 1, "stock": 15},
    {"name": "Hand Soap Dispenser", "name_arabic": "حامل صابون يد", "category": "Cleaning", "price": 15.0, "moq": 10, "stock": 300},
    {"name": "Broom Set 3pc", "name_arabic": "طقم مكنس (3 قطع)", "category": "Cleaning", "price": 20.0, "moq": 10, "stock": 400},
    {"name": "Cleaning Cart", "name_arabic": "عربة تنظيف", "category": "Cleaning", "price": 380.0, "moq": 1, "stock": 10},
    {"name": "Paper Towel 30pk", "name_arabic": "مناديل ورق (30 حزمة)", "category": "Cleaning", "price": 45.0, "moq": 5, "stock": 200},
    {"name": "Air Freshener 12pk", "name_arabic": "معطر هواء (12 حبة)", "category": "Cleaning", "price": 35.0, "moq": 10, "stock": 500},
    {"name": "Drain Cleaner 1L", "name_arabic": "公网安备 مجارٍ 1 لتر", "category": "Cleaning", "price": 12.0, "moq": 20, "stock": 300},
    {"name": "Dustpan Brush Set", "name_arabic": "طقم الممسحة والفرشاة", "category": "Cleaning", "price": 10.0, "moq": 10, "stock": 500},
    # MEDICAL SUPPLIES (15)
    {"name": "First Aid Kit 50pc", "name_arabic": "حقيبة اسعافات اولية", "category": "Medical Supplies", "price": 85.0, "moq": 3, "stock": 200},
    {"name": "Disposable Gloves 100", "name_arabic": "قفازات طبية (100 زوج)", "category": "Medical Supplies", "price": 25.0, "moq": 10, "stock": 1000},
    {"name": "Surgical Mask 50pc", "name_arabic": "كمامات جراحية (50)", "category": "Medical Supplies", "price": 15.0, "moq": 10, "stock": 2000},
    {"name": "Blood Pressure Monitor", "name_arabic": "جهاز قياس ضغط الدم", "category": "Medical Supplies", "price": 120.0, "moq": 2, "stock": 50},
    {"name": "Thermometer Digital", "name_arabic": "ترمومتر رقمي", "category": "Medical Supplies", "price": 35.0, "moq": 5, "stock": 200},
    {"name": "Bandage Roll 10cm", "name_arabic": "شاش 10 سم (100 لفافة)", "category": "Medical Supplies", "price": 30.0, "moq": 10, "stock": 500},
    {"name": "Pulse Oximeter", "name_arabic": "جهاز قياس النبض", "category": "Medical Supplies", "price": 65.0, "moq": 3, "stock": 150},
    {"name": "Stethoscope Pro", "name_arabic": "سماعة طبية احترافية", "category": "Medical Supplies", "price": 85.0, "moq": 2, "stock": 50},
    {"name": "Wheelchair Foldable", "name_arabic": "كرسي متحركة قابل للطي", "category": "Medical Supplies", "price": 350.0, "moq": 1, "stock": 15},
    {"name": "Medical Bed Manual", "name_arabic": "سرير طبي يدوي", "category": "Medical Supplies", "price": 850.0, "moq": 1, "stock": 5},
    {"name": "IV Stand", "name_arabic": "حامل منشط", "category": "Medical Supplies", "price": 95.0, "moq": 2, "stock": 30},
    {"name": "Oxygen Concentrator", "name_arabic": "مركز اكسجين 5 لتر", "category": "Medical Supplies", "price": 1200.0, "moq": 1, "stock": 8},
    {"name": "Nebulizer Machine", "name_arabic": "جهاز بخاخ", "category": "Medical Supplies", "price": 180.0, "moq": 2, "stock": 40},
    {"name": "Medical Waste Bin", "name_arabic": "صندوق نفايات طبية", "category": "Medical Supplies", "price": 45.0, "moq": 5, "stock": 100},
    {"name": "N95 Mask 20pc", "name_arabic": "كمامة N95 (20 كمامة)", "category": "Medical Supplies", "price": 35.0, "moq": 10, "stock": 1000},
    # SECURITY (15)
    {"name": "CCTV Camera 4MP", "name_arabic": "كاميرا مراقبة 4 ميجا", "category": "Security", "price": 180.0, "moq": 2, "stock": 100},
    {"name": "DVR 8-Channel", "name_arabic": "جهاز تسجيل 8 قنوات", "category": "Security", "price": 250.0, "moq": 1, "stock": 50},
    {"name": "Fire Extinguisher 6kg", "name_arabic": "طفاية حريق 6 كجم", "category": "Security", "price": 45.0, "moq": 5, "stock": 300},
    {"name": "Safe Box Hotel", "name_arabic": "خزنة فندقية", "category": "Security", "price": 280.0, "moq": 1, "stock": 30},
    {"name": "Access Control Keypad", "name_arabic": "لوحة تحكم وصول", "category": "Security", "price": 150.0, "moq": 2, "stock": 50},
    {"name": "Motion Sensor Alarm", "name_arabic": "حساس حركة وانذار", "category": "Security", "price": 85.0, "moq": 3, "stock": 100},
    {"name": "Door Lock Digital", "name_arabic": "قفل باب رقمي", "category": "Security", "price": 220.0, "moq": 1, "stock": 40},
    {"name": "Metal Detector", "name_arabic": "كاشف معادن يدوي", "category": "Security", "price": 350.0, "moq": 1, "stock": 20},
    {"name": "Barbed Wire 50m", "name_arabic": "سلك شائك 50 متر", "category": "Security", "price": 65.0, "moq": 5, "stock": 200},
    {"name": "Safety Vest 50pc", "name_arabic": "سترة سلامة (50 قطعة)", "category": "Security", "price": 12.0, "moq": 20, "stock": 500},
    {"name": "Fence Panel 2.5m", "name_arabic": "لوحة سياج 2.5 متر", "category": "Security", "price": 180.0, "moq": 5, "stock": 100},
    {"name": "Intercom System", "name_arabic": "نظام اتصال داخلي", "category": "Security", "price": 350.0, "moq": 1, "stock": 20},
    {"name": "Gate Motor", "name_arabic": "motor باب كروري", "category": "Security", "price": 450.0, "moq": 1, "stock": 15},
    {"name": "Cable Lock 1.8m", "name_arabic": "قفل كابل 1.8 متر", "category": "Security", "price": 35.0, "moq": 5, "stock": 200},
    {"name": "Emergency Button", "name_arabic": "زر طوارئ", "category": "Security", "price": 25.0, "moq": 10, "stock": 300},
    # PAINTING (15)
    {"name": "White Emulsion 20L", "name_arabic": "طلاء ابيض 20 لتر", "category": "Painting", "price": 85.0, "moq": 5, "stock": 300},
    {"name": "Primer Coat 20L", "name_arabic": "برايمر 20 لتر", "category": "Painting", "price": 65.0, "moq": 5, "stock": 200},
    {"name": "Spray Paint Box 12", "name_arabic": "طلاء بخاخ (12 بخاخة)", "category": "Painting", "price": 45.0, "moq": 10, "stock": 500},
    {"name": "Paint Roller Set 10pc", "name_arabic": "طقم رولر طلاء (10)", "category": "Painting", "price": 35.0, "moq": 5, "stock": 200},
    {"name": "Wall Putty 25kg", "name_arabic": "معجون حائط 25 كجم", "category": "Painting", "price": 42.0, "moq": 5, "stock": 300},
    {"name": "Painter Tape 48mm", "name_arabic": "شريط رسام 48 ملم", "category": "Painting", "price": 8.0, "moq": 20, "stock": 1000},
    {"name": "Sandpaper 100pc", "name_arabic": "ورقة صنفرة (100 ورقة)", "category": "Painting", "price": 25.0, "moq": 10, "stock": 500},
    {"name": "Texture Paint 20L", "name_arabic": "طلاء بارز 20 لتر", "category": "Painting", "price": 120.0, "moq": 3, "stock": 100},
    {"name": "Paint Spray Gun", "name_arabic": "مسدس رش طلاء", "category": "Painting", "price": 180.0, "moq": 1, "stock": 30},
    {"name": "Anti-Rust Paint 20L", "name_arabic": "طلاء مضاد للصدأ 20 لتر", "category": "Painting", "price": 95.0, "moq": 5, "stock": 150},
    {"name": "Wood Stain 5L", "name_arabic": "بقع خشب 5 لتر", "category": "Painting", "price": 55.0, "moq": 5, "stock": 100},
    {"name": "Varnish Clear 5L", "name_arabic": "ورنيش شفاف 5 لتر", "category": "Painting", "price": 48.0, "moq": 5, "stock": 100},
    {"name": "Paint Brush Set 12pc", "name_arabic": "طقم فرش طلاء (12)", "category": "Painting", "price": 30.0, "moq": 5, "stock": 300},
    {"name": "Caulk Gun", "name_arabic": "مسدس سيليكون", "category": "Painting", "price": 25.0, "moq": 10, "stock": 200},
    {"name": "Color Chart Deck", "name_arabic": "كتيب الالوان", "category": "Painting", "price": 15.0, "moq": 5, "stock": 100},
    # PLUMBING (15)
    {"name": "PVC Pipe 4in 6m", "name_arabic": "انبوب PVC 4 بوصة 6 متر", "category": "Plumbing", "price": 45.0, "moq": 10, "stock": 500},
    {"name": "Water Heater 80L", "name_arabic": "سخان ماء 80 لتر", "category": "Plumbing", "price": 450.0, "moq": 1, "stock": 20},
    {"name": "Toilet Complete Set", "name_arabic": "طقم حمام كامل", "category": "Plumbing", "price": 350.0, "moq": 1, "stock": 30},
    {"name": "Sink Kitchen Steel", "name_arabic": "حوض مطبخ استانلس", "category": "Plumbing", "price": 180.0, "moq": 1, "stock": 30},
    {"name": "Faucet Mixer Kitchen", "name_arabic": "حنفيية خلاط مطبخ", "category": "Plumbing", "price": 95.0, "moq": 2, "stock": 100},
    {"name": "Shower Set Rain", "name_arabic": "طقم دش", "category": "Plumbing", "price": 150.0, "moq": 2, "stock": 50},
    {"name": "Pressure Pump 1HP", "name_arabic": "مضخة ضغط 1 حصان", "category": "Plumbing", "price": 280.0, "moq": 1, "stock": 30},
    {"name": "Water Filter House", "name_arabic": "فلتر ماء للمنزل", "category": "Plumbing", "price": 350.0, "moq": 1, "stock": 20},
    {"name": "Ball Valve 1in Brass", "name_arabic": "صمام كُرة 1 بوصة نحاس", "category": "Plumbing", "price": 18.0, "moq": 10, "stock": 500},
    {"name": "Flexible Hose 1.5m", "name_arabic": "خرطوم مرن 1.5 متر", "category": "Plumbing", "price": 12.0, "moq": 10, "stock": 500},
    {"name": "Drain Cover Steel", "name_arabic": "غطاء بالوعة استانلس", "category": "Plumbing", "price": 25.0, "moq": 5, "stock": 200},
    {"name": "Pipe Wrench 18in", "name_arabic": "مفتاح انابيب 18 بوصة", "category": "Plumbing", "price": 55.0, "moq": 2, "stock": 100},
    {"name": "Float Valve 1in", "name_arabic": "صمام طفو 1 بوصة", "category": "Plumbing", "price": 22.0, "moq": 10, "stock": 300},
    {"name": "Tank Pump 3/4HP", "name_arabic": "مضخة خزان 3/4 حصان", "category": "Plumbing", "price": 220.0, "moq": 1, "stock": 25},
    {"name": "Check Valve 2in", "name_arabic": "صمام ارجاع 2 بوصة", "category": "Plumbing", "price": 35.0, "moq": 5, "stock": 150},
    # EXTRA Building Materials (5)
    {"name": "Glass Panel 3mm", "name_arabic": "لوحة زجاج 3 ملم", "category": "Building Materials", "price": 35.0, "moq": 5, "stock": 200},
    {"name": "PVC Ceiling Panel", "name_arabic": "لوحة سقف PVC", "category": "Building Materials", "price": 18.0, "moq": 20, "stock": 1000},
    {"name": "Granite Slab", "name_arabic": "لوحGranite", "category": "Building Materials", "price": 120.0, "moq": 3, "stock": 50},
    {"name": "Steel H-Beam 200", "name_arabic": "حديد H-Beam 200", "category": "Building Materials", "price": 850.0, "moq": 2, "stock": 30},
    {"name": "Insulation Foam", "name_arabic": "لوح عازل فوم", "category": "Building Materials", "price": 25.0, "moq": 10, "stock": 500},
    # EXTRA Electrical (5)
    {"name": "Solar Inverter 5kW", "name_arabic": "عاكس شمسي 5 كيلو واط", "category": "Electrical", "price": 3500.0, "moq": 1, "stock": 10},
    {"name": "Battery 200Ah Solar", "name_arabic": "بطارية شمسية 200 امبير", "category": "Electrical", "price": 850.0, "moq": 1, "stock": 20},
    {"name": "Cable Gland PG13", "name_arabic": "غطاء كابل PG13", "category": "Electrical", "price": 2.5, "moq": 100, "stock": 5000},
    {"name": "MCB Breaker 20A", "name_arabic": "قواطع MCB 20 امبير", "category": "Electrical", "price": 12.0, "moq": 20, "stock": 1000},
    {"name": "Cable Lugs 10mm", "name_arabic": "تطريز كابل 10 ملم", "category": "Electrical", "price": 15.0, "moq": 10, "stock": 500},
]

if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(__file__) + '/../src/backend')
    from seed_data import PRODUCTS
    print(f"Current products: {len(PRODUCTS)}")
    print(f"Adding: {len(NEW_PRODUCTS)}")
    print(f"Total: {len(PRODUCTS) + len(NEW_PRODUCTS)}")
